### ISSUE TITLE
java.net.SocketException: Unexpected end of file from server

### ISSUE THREAD

**Issue by govelogo** [gesellix-docker/gradle-docker-plugin-example#3]
I tried to get the out-of-box gradle tasks working on my Win7 machine. In a cmd window, I did

set DOCKER_HOST=tcp://192.168.59.103:2376

then run "gradlew version", and I got this error message,

Execution failed for task ':version'.
> java.net.SocketException: Unexpected end of file from server

Here is the stacktrace info ... any ideas? thanks!! --David

Caused by: java.net.SocketException: Unexpected end of file from server
        at de.gesellix.docker.client.LowLevelDockerClient.readHeaders(LowLevelDockerClient.groovy:195)
        at de.gesellix.docker.client.LowLevelDockerClient$readHeaders$3.callCurrent(Unknown Source)
        at de.gesellix.docker.client.LowLevelDockerClient.handleResponse(LowLevelDockerClient.groovy:120)
        at de.gesellix.docker.client.LowLevelDockerClient.request(LowLevelDockerClient.groovy:115)
        at de.gesellix.docker.client.LowLevelDockerClient$request$1.callCurrent(Unknown Source)
        at de.gesellix.docker.client.LowLevelDockerClient.get(LowLevelDockerClient.groovy:50)
        at de.gesellix.docker.client.LowLevelDockerClient$get.call(Unknown Source)
        at de.gesellix.docker.client.DockerClientImpl.version(DockerClientImpl.groovy:54)
        at de.gesellix.docker.client.DockerClient$version.call(Unknown Source)
        at de.gesellix.gradle.docker.tasks.DockerVersionTask.version(DockerVersionTask.groovy:21)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        ... 54 more
Caused by: java.net.SocketException: Unexpected end of file from server
        at de.gesellix.docker.client.LowLevelDockerClient.readHeaders(LowLevelDockerClient.groovy:193)
        ... 64 more

**Comment by govelogo** [comment]
solved by set DOCKER_TLS_VERIFY and DOCKER_CERT_PATH env variables
